# Generated by Django 5.1.6 on 2025-03-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Type1', 'Type 1'), ('Type2', 'Type 2')], default='Type1', max_length=50),
        ),
    ]
