# Generated by Django 5.1.6 on 2025-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency_symbol',
            field=models.CharField(choices=[('$', '$ - US Dollar'), ('€', '€ - Euro'), ('£', '£ - British Pound'), ('¥', '¥ - Japanese Yen'), ('₹', '₹ - Indian Rupee'), ('₩', '₩ - South Korean Won'), ('KSh', 'KSh - Kenyan Shilling')], default='$', max_length=5),
        ),
    ]
