# Generated by Django 4.2.7 on 2025-10-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0004_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Pieces"),
                    ("kg", "Kilograms"),
                    ("ltr", "Liters"),
                    ("box", "Boxes"),
                    ("m", "Meters"),
                    ("pack", "Packs"),
                    ("bottle", "Bottles"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="VATCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "vat_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Rate (16%)"),
                            ("zero", "Zero Rate (0%)"),
                            ("exempt", "Exempt from VAT"),
                            ("reduced", "Reduced Rate"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_categories",
                        to="pos_app.business",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "VAT Categories",
                "unique_together": {("business", "code")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="vat_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="pos_app.vatcategory",
            ),
        ),
    ]
