# Generated by Django 4.2.7 on 2025-10-03 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pos_app", "0005_add_vat_system_and_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum credit allowed for this customer",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="current_debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current outstanding debt",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit/Debit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_payment", "Mobile Payment"),
                    ("loyalty_points", "Loyalty Points"),
                    ("credit", "Credit Customer"),
                    ("mixed", "Mixed Payment"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_reference", models.CharField(max_length=50, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Payment"),
                            ("card", "Card Payment"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_payment", "Mobile Payment"),
                            ("credit_note", "Credit Note Applied"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_payments",
                        to="pos_app.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_payments",
                        to="pos_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_note_number", models.CharField(max_length=50, unique=True)),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("return", "Return"),
                            ("adjustment", "Adjustment"),
                            ("discount", "Discount"),
                        ],
                        default="refund",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                (
                    "is_applied",
                    models.BooleanField(
                        default=False,
                        help_text="Whether credit has been applied to customer account",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="pos_app.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_notes",
                        to="pos_app.customer",
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_notes",
                        to="pos_app.sale",
                    ),
                ),
            ],
        ),
    ]
