# Generated by Django 4.2.7 on 2025-10-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0006_customer_credit_limit_customer_current_debt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="default_vat_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_businesses",
                to="pos_app.vatcategory",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="enable_vat",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="kra_pin",
            field=models.CharField(
                blank=True,
                help_text="KRA PIN for VAT compliance",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="show_vat_on_receipt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="vat_inclusive_pricing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="VAT registration number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="vat_rounding",
            field=models.CharField(
                choices=[("round", "Round"), ("floor", "Floor"), ("ceil", "Ceiling")],
                default="round",
                max_length=10,
            ),
        ),
    ]
