# Generated by Django 4.2.7 on 2025-10-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos_app", "0007_businesssettings_default_vat_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtpayment",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debt_payments",
                to="pos_app.sale",
            ),
        ),
    ]
